version: '3.8'

services:
  web:
    build: .
    container_name: arteris_motor_formulas
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
    command: bash -c "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    depends_on:
      - redis
      
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data: